# Generated by Django 3.1.4 on 2021-01-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'managed': True},
        ),
    ]
